### ISSUE TITLE
Website Feedback

### ISSUE THREAD

**Issue by JamesPHoughton** [Watts-Lab/deliberation-website#10]
I'm looking for feedback on this:

https://deliberation-lab.org/

**Comment by linneagandhi** [comment]
This is so professional looking @JamesPHoughton !! The thing I would love to see but probably is super hard to do is a dynamic demo - can people enter a "fake" chat room and explore it? Or, more simply, a video that is <1 min that shows diff features? (like the photos you have, but IMO seeing the interface live / dynamically is even more impressive! further, if people can see it is easy to onboard into using the tool, that may increase uptake?)

**Comment by markwhiting** [comment]
1. University logos are rather close to each other. Uncomfortably close?
2. One of the logos in the footer is not loading
3. This is not a problem, but it feels very research centric. e.g., 
   > An open-science intiative to rapidly advance scientific understanding of small group deliberation
   
   This is fine but feels like you're putting yourself in a bucket you don't need to be in. e.g., "rapidly advance scientific understanding", why not just "An open science for understanding deliberation" 
4. intiative → initiative
5. The shortness of the first study on Studies page means the image gets in the way of the second heading. I think this would be better fixed.
6. The bottom image on that page also goes into the footer, which makes it look like you can scroll but you can not
7. I think tools should start with a vision segment that has a diagram. It seems like the "A high-throughput virtual laboratory" section feels like its aiming at that but I think its a little abstract and the images don't tell the story of the (potential) design space. 
8. I think the code snip on the tools section should be colored so the structure stands out more
9. The collaboration tab is interesting but feels a bit aspirational. Like "we hope to do..." or "we will do ...". I wonder if being a bit simpler and more direct would be helpful. 
10. This last point relates to a broader one: who is the audience you and what are you trying to get them to do or think? It feels like some tabs speak to similar audiences at different levels of refinement or clarity.

**Comment by xehu** [comment]
James, this looks amazing!!! Wonderful work.

Here are a few pieces of feedback:

1. The footer looks really weirdly organized --- there are logos at 3 different levels, and the Wharton logo is broken. I also feel like the "Privacy Policy" feels a bit out of place.

![Image](https://github.com/Watts-Lab/deliberation-website/assets/28793641/6a7f9bef-9af3-408c-9410-ee6f52a01dd3)

2. For long pages (like Tools), it might be helpful to have a scrollable table of contents so that users can get a sense of what is in the page, and jump to a relevant section.

3. I think a demo or demo video under "Tools" could go a long way! Currently, you only have static images, but I am almost always impressed by your videos/gifs! Walking the user through an entire process might be really informative in showing the tool's power.

4. On the main page, WashU's logo is so tiny relative to the rest --- it makes it feel less important.

5. On the main page: It’s goal —> Its goal


6. Bad influence (under studies) —> link Dean’s website/group, as you do for Netta Weinstein

- Same goes for linking yours and Duncan’s names on “Am I talking too much?”

**Comment by xehu** [comment]
I'm realizing that a few of my comments overlap with those of Mark and Linnea --- great minds think alike?? :)

**Comment by JamesPHoughton** [comment]
Thanks for all of the great feedback, everyone. I used this at IACM with very good effect - it was really helpful to be able to direct people to it who wanted more information, like a "flyer". 

Breaking out a few remaining suggestions to their own issues
- https://github.com/Watts-Lab/deliberation-website/issues/17
- https://github.com/Watts-Lab/deliberation-website/issues/16
- https://github.com/Watts-Lab/deliberation-website/issues/12
